version: '3'

services: 
  broker_service:
    build: 
      context: ./../broker_service
      dockerfile: ./../broker_service/broker_service.dockerfile
    restart: always
    ports: 
      - "8080:80"
    deploy: 
      mode: replicated
      replicas: 1

  authentication_service:
    build: 
      context: ./../authentication_service
      dockerfile: ./../authentication_service/authentication_service.dockerfile
    restart: always
    ports: 
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment: 
      DSN: "host=postgres port=5432 password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"


  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/