version: '3'

services: 
  broker_service:
    build: 
      context: ./../broker_service
      dockerfile: ./../broker_service/broker_service.dockerfile
    restart: always
    ports: 
      - "8080:80"
    deploy: 
      mode: replicated
      replicas: 1

  authentication-service:
    build: 
      context: ./../authentication_service
      dockerfile: ./../authentication_service/authentication_service.dockerfile
    restart: always
    ports: 
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment: 
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"


  postgres:
    image: 'postgres:latest'
    ports:
      - "5431:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin       
    ports:
      - "8085:80"                
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin
  